lr: 0.00005 # more_layers: 0.00005, one layer: 0.0001
seed: 1
if_cuda: True
gamma: 0.5
log_dir: 'scissors_11_12'
train_batch: 19200
val_batch: 19200
test_batch: 19200
task_batch: 38400
num_workers: 16
model_name: 'state-condition'
data_filepath: 'data/scissors_10893'
lr_schedule: [10000000]
num_gpus: 1
epochs: 300
loss_type: 'siren_sdf'
dof: 1
coord_system: 'cartesian'
tag: 'new-global-siren-sdf'
cache_to: cpu